services:
  fhir-server:
    image: hapiproject/hapi:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    container_name: "${SANDBOX_NAME}_sandbox"
    ports:
     # - 8787:8080
      - "${FHIR_SERVER_PORT}:8080"
    env_file:
      - .env
#    deploy:
#      resources:
#        limits:
#          cpus: '1'   # Limits the container to use only 50% of a single CPU
    environment:
     SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yml'
    volumes:
      - ./conf:/data/hapi
      - ./web:/custom
      - ./apps:/apps
    depends_on:
        - db

  db:
    image: postgres:latest
    restart: always
    container_name: "db_${SANDBOX_NAME}_sandbox"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hapi
      - POSTGRES_ROOT_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ember-ext:
    image: jkiddo/ember:latest
    environment:
      - location=https://hl7.eu/fhir/extensions/package.tgz
      - serverBase=http://fhir-server:8080/eubase/fhir
      - usePUT=true

  ember-base:
    image: jkiddo/ember:latest
    environment:
      - location=https://hl7.eu/fhir/base-r5/package.tgz
      - serverBase=http://fhir-server:8080/eubase/fhir
      - usePUT=true


  ember-imaging:
    image: jkiddo/ember:latest
    environment:
      - location=https://hl7.eu/fhir/imaging-r5/package.tgz
      - serverBase=http://fhir-server:8080/eubase/fhir
      - usePUT=true

  ember-mpd:
    image: jkiddo/ember:latest
    environment:
      - location=https://hl7.eu/fhir/mpd-r5/package.tgz
      - serverBase=http://fhir-server:8080/eubase/fhir
      - usePUT=true
