server:
  servlet:
    context-path: /questionnaire-server

hapi:
  fhir:
    server_address: https://sandbox.hl7europe.eu/questionnaire-server/fhir
#    fhir_version: R5
#    supported_resource_types:
#      - ActivityDefinition
#      - CodeSystem
#      - Library
#      - Measure
#      - OperationDefinition
#      - PlanDefinition
#      - Questionnaire
#      - QuestionnaireResponse
#      - SearchParameter
#      - StructureDefinition
#      - Subscription
#      - ValueSet

    ### This flag when enabled to true, will avail evaluate measure operations from CR Module.
    ### Flag is false by default, can be passed as command line argument to override.
    cr:
      enabled: true


    tester:
      home:
        name: Local Tester
        server_address: https://sandbox.hl7europe.eu/questionnaire-server/fhir
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4

      global:
        name: Global Tester
        server_address: "https://hapi.fhir.org/baseR4"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
