services:
  fhir-server:
    image: hapiproject/hapi:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    container_name: pcsp-sandbox
    ports:
      - 9797:8080
  #  deploy:
   #   resources:
    #    limits:
     #     cpus: '1'   # Limits the container to use only 50% of a single CPU
    environment:
     SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yml'
    volumes:
      - ./conf:/data/hapi
      - ./web:/custom
      - ./apps:/apps
    depends_on:
        - db

  db:
    image: postgres:latest
    restart: always
    container_name: db_pcsp_sandbox
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hapi
      - POSTGRES_ROOT_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ember:
    image: jkiddo/ember:latest
    environment:
      - location=https://hl7.eu/fhir/ig/pcsp/package.tgz
      - serverBase=http://fhir-server:8080/pcsp/fhir
      - usePUT=true
